"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { useState } from "react";
import ReduxProvider from "@/store/redux-provider";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools/production";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryClient = new QueryClient();
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>
          <QueryClientProvider client={queryClient}>
            <div className="min-w-full">
              <div className="w-full fixed z-20">
                <Navbar />
              </div>
            </div>
            {children}
            <ReactQueryDevtools
              initialIsOpen={false}
              buttonPosition="bottom-left"
            />
          </QueryClientProvider>
        </body>
      </ReduxProvider>
    </html>
  );
}
